name: ci

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    name: OTP ${{matrix.pair.otp}} / Elixir ${{matrix.pair.elixir}}
    strategy:
      matrix:
        include:
          - pair:
              elixir: '1.10'
              otp: '23.2'
          - pair:
              elixir: '1.11'
              otp: '23.2'
          - pair:
              elixir: '1.12'
              otp: '24.1'
            lint: lint
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.pair.otp}}
          elixir-version: ${{matrix.pair.elixir}}
      - run: mix deps.get
      - run: mix format --check-formatted
        if: ${{ matrix.lint }}
      - run: mix test
